In [12]:
#Steps to follow when working with real world data
#1. Load data
#2. Look at data to remove irrelevant data
#3. Finding missing values 
#4. Understand categories
#5. Pick a model

# Lets look at a real world problem such as home price prediction

In [13]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [14]:
##Load data
import pandas as pd

# Load the data
df = pd.read_csv('gdrive/MyDrive/new.csv')

# Lets look at the data
df.head()

     row_id  time_id  investment_id  ...     f_297     f_298     f_299
0  472_2548      472           2548  ... -0.562254  1.122550 -0.624696
1  472_2549      472           2549  ... -0.642916  0.868634  2.413024
2  472_2550      472           2550  ... -0.568142  1.097748 -0.671822
3  472_2553      472           2553  ... -0.590567 -0.115878 -0.565149
4  472_2554      472           2554  ...  0.911922  0.000000 -0.795572

[5 rows x 304 columns]

In [15]:
import tensorflow as tf
tf.test.gpu_device_name()

''

In [16]:
y = df.target

In [17]:
x = df
x = x.drop(['target', 'row_id'], axis=1)

In [18]:
print(x.shape)
print(y.shape)

(2141412, 302)
(2141412,)

In [19]:
!pip install pytorch-tabnet
import pandas as pd
import numpy  as np
from pytorch_tabnet.tab_model import TabNetRegressor

Requirement already satisfied: pytorch-tabnet in /usr/local/lib/python3.7/dist-packages (3.1.1)
Requirement already satisfied: numpy<2.0,>=1.17 in /usr/local/lib/python3.7/dist-packages (from pytorch-tabnet) (1.19.5)
Requirement already satisfied: scikit_learn>0.21 in /usr/local/lib/python3.7/dist-packages (from pytorch-tabnet) (1.0.2)
Requirement already satisfied: tqdm<5.0,>=4.36 in /usr/local/lib/python3.7/dist-packages (from pytorch-tabnet) (4.62.3)
Requirement already satisfied: scipy>1.4 in /usr/local/lib/python3.7/dist-packages (from pytorch-tabnet) (1.4.1)
Requirement already satisfied: torch<2.0,>=1.2 in /usr/local/lib/python3.7/dist-packages (from pytorch-tabnet) (1.10.0+cu111)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit_learn>0.21->pytorch-tabnet) (1.1.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from torch<2.0,>=1.2->pytorch-tabnet) (3.10.0.2)

In [20]:
# time series split

In [21]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_absolute_error
import pickle
filename = 'finalized_model.sav'
regressor = TabNetRegressor(verbose=0,seed=42)
pickle.dump(regressor, open(filename, 'wb'))

In [22]:
# Garbage Collector - use it like gc.collect()
import gc

In [23]:
gc.collect()

302

In [11]:

tscv = TimeSeriesSplit(n_splits = 20)
rmse = []
CV_score_array    =[]
predictions_array =[]

for train_index, test_index in tscv.split(x):
    X_train, X_valid = x.iloc[train_index], x.iloc[test_index]
    y_train, y_valid = y[train_index], y[test_index]

    X_train      = X_train.to_numpy()
    y_train = y_train.to_numpy().reshape(-1, 1)
    
    X_valid      = X_valid.to_numpy()
    y_valid = y_valid.to_numpy().reshape(-1, 1)
    
    regressor = pickle.load(open(filename, 'rb'))
    regressor.fit(X_train=X_train, y_train=y_train,
              eval_set=[(X_valid, y_valid)],
              patience=300, max_epochs=100,
              eval_metric=['rmse'])
    pickle.dump(regressor, open(filename, 'wb'))

    predictions = regressor.predict(X_valid)
    # calculate Pearson's correlation
    #corr, _ = pearsonr(y_valid, predictions)
    #print('Pearsons correlation: %.3f' % corr)
   
    CV_score_array.append(regressor.best_cost)
    print("The CV score is %.5f" % np.mean(CV_score_array,axis=0) )
    predictions_array.append(np.expm1(predictions))

Stop training because you reached max_epochs = 100 with best_epoch = 5 and best_val_0_rmse = 0.92789
Best weights from best epoch are automatically used!

NameError: ignored

# New Section

In [24]:
print("Predictions = " , predictions )

Predictions =  [[ 0.02403365]
 [-0.16116937]
 [-0.07160947]
 ...
 [-0.08244248]
 [-0.01684965]
 [ 0.03490504]]

In [25]:
print("Predictions = " , predictions )

Predictions =  [[ 0.02403365]
 [-0.16116937]
 [-0.07160947]
 ...
 [-0.08244248]
 [-0.01684965]
 [ 0.03490504]]

In [26]:
filename = 'finalized_model.sav'
pickle.dump(regressor, open(filename, 'wb'))

In [27]:

# load the model from disk
regressor = pickle.load(open(filename, 'rb'))
#result = loaded_model.score(X_test, Y_test)
#print(result)